"""initial tables

Revision ID: f287cb1bc83c
Revises: 
Create Date: 2026-04-12 08:45:24.109744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f287cb1bc83c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('related_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_platform_score', 'trends', ['platform', sa.literal_column('trend_score DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'ultra', name='subscriptiontier'), nullable=False),
    sa.Column('growth_profile', sa.JSON(), nullable=False),
    sa.Column('voice_profile', sa.JSON(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('virality_score', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_seeds_user_id'), 'content_seeds', ['user_id'], unique=False)
    op.create_table('content_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('thread_url', sa.String(), nullable=False),
    sa.Column('thread_title', sa.Text(), nullable=False),
    sa.Column('drafted_reply', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('opportunity_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'posted', 'skipped', name='opportunitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_opportunities_user_id'), 'conversation_opportunities', ['user_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('github', 'notion', 'figma', 'google_drive', 'google_calendar', 'linkedin', 'twitter', 'instagram', name='integrationplatform'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('platform_username', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_user_platform', 'integrations', ['user_id', 'platform'], unique=True)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('narrative_arcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('arc_title', sa.String(length=255), nullable=False),
    sa.Column('arc_description', sa.Text(), nullable=False),
    sa.Column('project_context', sa.Text(), nullable=True),
    sa.Column('total_stages', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'paused', name='arcstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('relationship_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_username', sa.String(length=255), nullable=False),
    sa.Column('target_platform', sa.String(length=50), nullable=False),
    sa.Column('target_follower_count', sa.Integer(), nullable=True),
    sa.Column('alignment_score', sa.Integer(), nullable=True),
    sa.Column('relationship_stage', sa.Enum('identified', 'warming', 'engaged', 'connected', name='relationshipstage'), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('last_engaged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'imported', 'approved_post', name='tunesamplesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tune_samples_user_id'), 'tune_samples', ['user_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seed_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('linkedin', 'twitter', 'instagram', 'youtube', 'reddit', name='contentplatform'), nullable=False),
    sa.Column('content_type', sa.Enum('post', 'thread', 'carousel', 'video_script', 'article', name='contenttype'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('variation_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'scheduled', 'published', 'failed', name='contentstatus'), nullable=False),
    sa.Column('virality_score', sa.Integer(), nullable=False),
    sa.Column('virality_reasoning', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('narrative_arc_id', sa.UUID(), nullable=True),
    sa.Column('arc_stage', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['narrative_arc_id'], ['narrative_arcs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seed_id'], ['content_seeds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_ready', 'content', ['scheduled_time'], unique=False, postgresql_where=sa.text("scheduled_time IS NOT NULL AND status = 'approved'"))
    op.create_index('idx_user_id_status', 'content', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_content_status'), 'content', ['status'], unique=False)
    op.create_index(op.f('ix_content_user_id'), 'content', ['user_id'], unique=False)
    op.create_table('calendar_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='calendarstatus'), nullable=True),
    sa.Column('engagement_prediction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('skippy', 'snooks', 'meta', 'refine', 'support', name='chatmode'), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('content_variable', sa.String(length=255), nullable=False),
    sa.Column('control_content_id', sa.UUID(), nullable=True),
    sa.Column('test_content_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('learning', sa.Text(), nullable=True),
    sa.Column('applied_to_profile', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_content_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_content_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_analytics')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('calendar_entries')
    op.drop_index(op.f('ix_content_user_id'), table_name='content')
    op.drop_index(op.f('ix_content_status'), table_name='content')
    op.drop_index('idx_user_id_status', table_name='content')
    op.drop_index('idx_scheduled_ready', table_name='content', postgresql_where=sa.text("scheduled_time IS NOT NULL AND status = 'approved'"))
    op.drop_table('content')
    op.drop_index(op.f('ix_tune_samples_user_id'), table_name='tune_samples')
    op.drop_table('tune_samples')
    op.drop_table('relationship_targets')
    op.drop_table('onboarding_sessions')
    op.drop_table('narrative_arcs')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index('idx_integration_user_platform', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_conversation_opportunities_user_id'), table_name='conversation_opportunities')
    op.drop_table('conversation_opportunities')
    op.drop_table('content_templates')
    op.drop_index(op.f('ix_content_seeds_user_id'), table_name='content_seeds')
    op.drop_table('content_seeds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_trend_platform_score', table_name='trends')
    op.drop_table('trends')
    # ### end Alembic commands ###
