#!/usr/bin/env node
/**
 * CozyJet Next.js launcher — fetches secrets from Doppler before starting.
 *
 * Works exactly like backend/start.py but for Node/Next.js.
 * Writes secrets to .env.local so Next.js picks them up at startup.
 * .env.local is gitignored — secrets never hit GitHub.
 *
 * Usage:
 *   node scripts/start-dev.js             (dev, port 5000)
 *   DOPPLER_CONFIG=prd node scripts/start-dev.js
 */

const https = require("https");
const fs = require("fs");
const path = require("path");
const { execSync, spawn } = require("child_process");

const DOPPLER_PROJECT = "cozyjet-ai";
const DOPPLER_CONFIG = process.env.DOPPLER_CONFIG || "dev";
const ENV_LOCAL_PATH = path.join(__dirname, "..", ".env.local");

function fetchDopplerSecrets(token) {
  return new Promise((resolve, reject) => {
    const url = new URL(
      `https://api.doppler.com/v3/configs/config/secrets/download` +
        `?format=json&include_dynamic_secrets=true&dynamic_secrets_ttl_sec=1800` +
        `&project=${DOPPLER_PROJECT}&config=${DOPPLER_CONFIG}`
    );
    const options = {
      hostname: url.hostname,
      path: url.pathname + url.search,
      headers: { Authorization: `Bearer ${token}` },
      timeout: 15000,
    };
    const req = https.get(options, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => {
        if (res.statusCode !== 200) {
          reject(new Error(`Doppler HTTP ${res.statusCode}: ${data}`));
        } else {
          resolve(JSON.parse(data));
        }
      });
    });
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("Doppler request timed out")); });
  });
}

function writeEnvLocal(secrets) {
  const lines = ["# Auto-generated by scripts/start-dev.js — DO NOT COMMIT"];
  let count = 0;
  for (const [key, value] of Object.entries(secrets)) {
    if (key.startsWith("DOPPLER_") || value == null) continue;
    // Escape newlines inside values
    const safe = String(value).replace(/\n/g, "\\n");
    lines.push(`${key}=${safe}`);
    count++;
  }
  fs.writeFileSync(ENV_LOCAL_PATH, lines.join("\n") + "\n", "utf8");
  console.log(`[doppler-start] Wrote ${count} secret(s) to .env.local`);
}

async function main() {
  const token = (process.env.DOPPLER_TOKEN || "").trim();

  if (token) {
    console.log(
      `[doppler-start] Fetching secrets from Doppler project=${DOPPLER_PROJECT} config=${DOPPLER_CONFIG} …`
    );
    try {
      const secrets = await fetchDopplerSecrets(token);
      writeEnvLocal(secrets);
    } catch (err) {
      console.warn(`[doppler-start] Doppler fetch failed: ${err.message} — continuing without it`);
    }
  } else {
    console.warn("[doppler-start] DOPPLER_TOKEN not set — skipping Doppler fetch");
  }

  // Start Next.js dev server
  console.log("[doppler-start] Starting Next.js on port 5000 …");
  const next = spawn(
    "npx",
    ["next", "dev", "--port", "5000", "--turbopack"],
    {
      stdio: "inherit",
      env: { ...process.env },
    }
  );

  process.on("SIGTERM", () => next.kill("SIGTERM"));
  process.on("SIGINT",  () => next.kill("SIGINT"));
  next.on("exit", (code) => process.exit(code ?? 0));
}

main().catch((err) => {
  console.error("[doppler-start] Fatal:", err);
  process.exit(1);
});
